version: "3.8"

services:
  app:
    build: .
    container_name: laravel_app
    restart: always
    working_dir: /var/www
    volumes:
      - .:/var/www
    depends_on:
      - node
    networks:
      - app_network

  node:
    image: node:18
    container_name: node_app
    working_dir: /var/www
    volumes:
      - .:/var/www
    command: ["sh", "-c", "npm install && npm run dev"]
    networks:
      - app_network

  nginx:
    image: nginx:latest
    container_name: nginx_server
    restart: always
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - app_network

networks:
  app_network:
    driver: bridge